function [var] = init_var()

    var = struct('id', [], 'adresse', [], 'format', 17, 'type', [], 'nom', [], ...
    'altitude', [], 'vitesse_air', [], 'vitesse_sol', [], 'cap', [], ...
    'taux', [], 'timeFlag', [], 'cprFlag', [], 'latitude', [], ...
    'longitude', [], 'trajectoire', []);
end